### ISSUE TITLE
Errors when using 'North Korea' in red coalition as template unit....

### ISSUE THREAD

**Issue by Quax456** [lukrop/GCICAP#1]
Hello,

it made me crazy to sort it out when I use your gcicap script it will throw errors when there are other Nations then Russia used in the red coalition......

And by the way: in your showcase mission the red SU27 CAP despawn after some minutes...havend took a deeper look why. But I think maybe they crash in the mountains due to less given altitude!?

Regards

**Comment by lukrop** [comment]
Thanks for the hint. Will have a look at it.

**Comment by lukrop** [comment]
MIST's dynAdd currently isn't handling country names with whitespaces correctly. I worked around it and propsed a fix to MIST upstream.

Regarding the SU27 CAP flights, I can't seem to reproduce the "despawn".
