### ISSUE TITLE
Despawn Handler: attempt to call method 'getGroup' (a nil value)

### ISSUE THREAD

**Issue by Marioshata** [lukrop/GCICAP#10]
Hey lukrop,
I am getting this error periodically while running my mission and I think it's GCICAP script related:

```
DCS: Mission script error: : [string "C:\Users\MARIOS~1\AppData\Local\Temp\DCS.openbeta\/~mis00004865"]:1277: attempt to call method 'getGroup' (a nil value)
stack traceback:
    [C]: in function 'getGroup'
    [string "C:\Users\MARIOS~1\AppData\Local\Temp\DCS.openbeta\/~mis00004865"]:1277: in function 'f'
    [string "C:\Users\MARIOS~1\AppData\Local\Temp\DCS.openbeta\/~mis00000785"]:861: in function 'onEvent'
    [string "Scripts/World/EventHandlers.lua"]:13: in function <[string "Scripts/World/EventHandlers.lua"]:11>
```

**Comment by lukrop** [comment]
Looks like the event handler isn't supplied with a initiator. Very strange. I'll add a check for that though I'm not sure if this should ever happen. Would you mind attaching the mission file here?

**Comment by Marioshata** [comment]
Still getting this error which seems to happen every time a random building from the scenery is destroyed.

**Comment by lukrop** [comment]
I think this would be related to MIST then. I'll have a look at the MIST code.

**Comment by lukrop** [comment]
This is still a problem and related to GCICAP itself.
