### ISSUE TITLE
script throws only exceptions

### ISSUE THREAD

**Issue by Quax456** [lukrop/GCICAP#13]
Dear LUKROP,

don't know why you decided to do your own MIST but either using your Version or the original I got one DEBUG-Error exception during runtime after the other....

So, I decide to get rid of this look for an other solution....

Regards

**Comment by lukrop** [comment]
First of all I didn't do "my own MIST" I just included the development version (available in the official MIST git repository) in the release package since GCICAP requires new features (Logger) available only in the development version of MIST. I did this so I didn't have to wait for Grimes to release a new MIST version.

Please provide any error messages you get if you want me to help you otherwise I'm unable to. I'm using the current master in several missions and it works flawlessly. Are you by any chance hit by #10, #11 fixed in 1ce3b5c98ecdb518a9f9b424a4d6c3d7d9493ae6?

**Comment by lotherk** [comment]
I also can confirm that this is working.

**Comment by Quax456** [comment]
This is what I get with your needed develop version of MIST
If I use the original GCICAP wont run too....

00353.540 ERROR   DCS: Mission script error: : [string "C:\Users\Thomas\AppData\Local\Temp\DCS\/~mis0000413A"]:6420: attempt to index global 'debug' (a nil value)

**Comment by lukrop** [comment]
GCICAP neither has 6420 lines nor does the word 'debug' occur in the script once.

It seems to be related to the development version of MIST itself. Line 6420 in this MIST version is

``` Lua
local dInfo = debug.getinfo(3)
```

This code is working on my machine (and others according to the forums). Are you running any mods? Which branch of DCS are you running?

**Comment by Quax456** [comment]
The only Mod I use is Slmod on my 1.5.3 release version....will give it a try to deactive it tomorrow!

If so, this could be the reason why Grimes doesnt answer your pull request for your expandations of MIST?

**Comment by lukrop** [comment]
Very strange. Somehow [debug](http://www.lua.org/pil/23.html) is missing in your LUA environment. Looks like it's sanitized somehow. I'm on the release version with no mods and the showcase missions are working flawlessly.

Grimes merged the pull request into the development branch. This is also the file which is packaged with the release archives.

**Comment by Quax456** [comment]
I have have sincerely to apologize......

SLMOD has something like:
sanitizeModule('debug')  -- So malicious missions can't break out of the sandbox and use LuaSocket.

at the end of their missionscripting.lua
this causes what the name says sanitizing the debug enviroment :-(
Someone should tell Grimes that this effects MIST as well!

As mentioned before, excuse me for a possible abusing of your work.

Best regards

**Comment by lukrop** [comment]
Alright, I'm going to send Grimes a pull request to fix this issue in the logger. Glad we found out. Thanks!
