### ISSUE TITLE
Wounded CAP never despawn

### ISSUE THREAD

**Issue by lukrop** [lukrop/GCICAP#14]
If you kill 1 out of 2 and the surviving aircraft RTB's then it will stay parked, never despawn and the cap will never replenish.

Tested on the provided sample mission at x10 speed, took about 5 minutes until it broke.

Thanks to Pikey for the report.

**Comment by lukrop** [comment]
Seems to still be a problem. :sob: 

http://www.twitch.tv/thebgpikester/v/52765116

**Comment by 42debug** [comment]
oh nice! i was trying to fix it using something like
`local function parkDestroy(event)
    if event.id==18 then
    if  not event.initiator:inAir() then
      event.initiator:destroy()
    end
  end
 end
mist.addEventHandler(parkDestroy)`

**Comment by lukrop** [comment]
Still no luck. Somehow the flights might never get tasked with RTB and therefore [this if clause](https://github.com/lukrop/GCICAP/blob/master/GCICAP.lua#L1307) never is fullfilled.

**Comment by lukrop** [comment]
Using the new garbage collector this issue should finally be solved. I couldn't reproduce any problems with latest master. I'll leave this open until some further testing is done.
