### ISSUE TITLE
GCI and CAP flights slow speed

### ISSUE THREAD

**Issue by Marioshata** [lukrop/GCICAP#2]
Hey lukrop,
First thanks for the rewrite, good performance increase compared to the "old" script.
GCI and CAP flights on station cruise at around -500 km/h (default speed new group) to their waypoints which seems a bit too low and cause problems (like excessive afterburner use from wingman(s)).

**Comment by lukrop** [comment]
What would you think would be a good speed? I can always force them to stop using the AB if they are on the CAP route.

**Comment by Marioshata** [comment]
Getting script error now...
733: '}' expected (to close '{' at line 729) near '='

**Comment by lukrop** [comment]
Script error should be fixed now. Speed with 650km/h and 700km/h is ok?

**Comment by Marioshata** [comment]
Gonna test to find best setting for jets, but as Stonehouse writes it won't be appropriate for WW2 planes and such.

**Comment by Marioshata** [comment]
New error:
734: '}' expected (to close '{' at line 729) near 'action'

**Comment by lukrop** [comment]
Fixed in b008463. Can't test my changes currently this is why such stupid things catch me.

**Comment by Marioshata** [comment]
You might want to increase default speeds a bit.
I will use these on my mission.
gcicap.cap.speed = 220 -- ~800 km/h
gcicap.gci.speed = 300 -- ~1000 km/h

This issue is now solved so I will close after a couple more tests.
