### ISSUE TITLE
CAP flights despawn problem

### ISSUE THREAD

**Issue by Marioshata** [lukrop/GCICAP#8]
Sometimes CAP flights decide to RTB on different air bases which prevents them from despawning and spawning new ones. As soon as you destroy those the script spawns their replacement. This also happens if 1 of the group is killed (if group set to 2) and the other 1 decides to RTB at some random air base. I am not sure if this is the case with GCI flights as all the ones I observed are returning to the same air base and despawning.

**Comment by lukrop** [comment]
Might be related to #7.

The script doesn't differntiate between airbases. It only checks if a unit has landed or crashed/pilot died. Maybe somehow the entry of the CAP in the flights table got removed prematurely.

**Comment by lukrop** [comment]
Didn't occur since 8ba6252.
