### ISSUE TITLE
CAP crash mid-air at spawn

### ISSUE THREAD

**Issue by lukrop** [lukrop/GCICAP#9]
If there are more CAP flights defined than zones and CAP flights start in-air at mission start they tend to crash at spawn because they are spawned at the same position.

Randomize spawn position a little bit to fix this.

**Comment by 457Stonehouse** [comment]
Was there any reason not to just randomise the starting alt between min and max cap alt? You have solved the issue differently but your way seems more complex and means every cap spawns at min cap alt (unless I am reading the code incorrectly which is possible)

**Comment by lukrop** [comment]
No particular reason. I'll see if we can make it simpler. If you want to you can look into it and send a pull-request. :)
